{{- define "spire-lib.spire-controller-manager-identity-nsselector" }}
key: "kubernetes.io/metadata.name"
{{-   if eq .type "base" }}
operator: NotIn
{{-   else }}
operator: In
{{-  end }}
values:
  {{ .namespaces | toYaml | nindent 2 }}
{{- end }}
{{- define "spire-lib.spire-controller-manager-identity-podselector" }}
{{-   if eq .type "oidc-discovery-provider" }}
matchLabels:
  release: {{ .releaseName }}
  release-namespace: {{ .releaseNamespace }}
  component: oidc-discovery-provider
{{-   else if eq .type "test-keys" }}
matchLabels:
  release: {{ .releaseName }}
  release-namespace: {{ .releaseNamespace }}
  component: test-keys
{{-   else }}
{}
{{-   end }}
{{- end }}
{{/* Takes in a dictionary with keys:
 * controllerManagerEnabled - enabled setting for the controller manager
 * releaseName - chart release name
 * releaseNamespace - chart release namespace
 * crNameOverride - custom resource name override setting
 * className - class name
 * clusterSPIFFEIDs - cluster SPIFFE IDs
 * namespaces - list of namespaces used durring install
*/}}
{{- define "spire-lib.cluster-spiffe-ids" }}
{{- $root := . }}
{{  $namespaces := .namespaces }}
{{- range $key, $value := .clusterSPIFFEIDs }}
{{-   range $skey, $svalue := $value }}
{{-     if not (has $skey (list "name" "annotations" "labels" "enabled" "type" "admin" "dnsNameTemplates" "downstream" "federatesWith" "jwtTTL" "namespaceSelector" "podSelector" "spiffeIDTemplate" "ttl" "workloadSelectorTemplates" "autoPopulateDNSNames")) }}
{{-       fail (printf "Unsupported property specified: %s" $skey) }}
{{-     end }}
{{-   end }}
{{-   if eq ($root.controllerManagerEnabled | toString) "true" }}
{{-     if or (not (hasKey $value "enabled")) (eq ($value.enabled | toString) "true") }}
{{-       $type := dig "type" "base" $value }}
{{-       if not (has $type (list "base" "raw" "oidc-discovery-provider" "test-keys")) }}
{{-         fail (printf "Type given: %s, must be one of [base, raw, oidc-discovery-provider, test-keys]" $type) }}
{{-       end }}
{{-       $namespaceSelector := deepCopy (dig "namespaceSelector" (dict) $value) }}
{{-       if ne $type "raw" }}
{{-         $namespaceSelector := merge $namespaceSelector (dict "matchExpressions" (list)) }}
{{-         $namespaceSelectorToAdd := include "spire-lib.spire-controller-manager-identity-nsselector" (dict "type" $type "namespaces" $namespaces) | fromYaml }}
{{-         $_ := set $namespaceSelector "matchExpressions" (append $namespaceSelector.matchExpressions $namespaceSelectorToAdd) }}
{{-       end }}
{{-       $podSelector := deepCopy (dig "podSelector" (dict) $value) }}
{{-       $podSelector := merge $podSelector (include "spire-lib.spire-controller-manager-identity-podselector" (dict "type" $type "releaseName" $root.releaseName "releaseNamespace" $root.releaseNamespace) | fromYaml ) }}
---
apiVersion: spire.spiffe.io/v1alpha1
kind: ClusterSPIFFEID
metadata:
  name: {{ $root.releaseNamespace }}-{{ default $root.releaseName $root.crNameOverride }}-{{ $key }}
  {{- with $value.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with $value.labels }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  className: {{ $root.className | quote }}
  {{- if and (hasKey $value "spiffeIDTemplate") (ne (len $value.spiffeIDTemplate) 0) }}
  spiffeIDTemplate: {{ $value.spiffeIDTemplate | quote }}
  {{- else }}
  spiffeIDTemplate: {{ $root.clusterSPIFFEIDs.default.spiffeIDTemplate | quote }}
  {{- end }}
  {{- with $value.federatesWith }}
  federatesWith:
  {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with $podSelector }}
  podSelector:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with $namespaceSelector }}
  namespaceSelector:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with $value.dnsNameTemplates }}
  dnsNameTemplates:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with $value.workloadSelectorTemplates }}
  workloadSelectorTemplates:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with $value.ttl }}
  ttl: {{ . | quote }}
  {{- end }}
  {{- with $value.jwtTTL }}
  jwtTtl: {{ . | quote }}
  {{- end }}
  {{- with $value.admin }}
  admin: {{ . }}
  {{- end }}
  {{- with $value.downstream }}
  downstream: {{ . }}
  {{- end }}
  {{- with $value.autoPopulateDNSNames }}
  autoPopulateDNSNames: {{ . }}
  {{- end }}
{{-     end }}
{{-   end }}
{{- end }}
{{- end }}
