{{- $root := . }}
{{- with .Values.kubeconfigs }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "spire-server.fullname" $root }}-kubeconfigs
  namespace: {{ include "spire-server.namespace" $root }}
data:
  {{- range $name, $value := . }}
  {{- if and (hasKey . "kubeconfig") (hasKey . "kubeconfigBase64") }}
  {{-   fail "You can not use both kubeconfig and kubeconfigBase64" }}
  {{- end }}
  {{- if (hasKey . "kubeconfig") }}
  {{ $name }}: {{ .kubeconfig | b64enc }}
  {{- else }}
  {{ $name }}: {{ .kubeconfigBase64 }}
  {{- end }}
  {{- end }}
{{- end }}
