#global:
#  spire:
#    clusterName: changeme
#    upstreamSpireAddress: spire-server.changeme

root-spire-server:
  kind: none
  controllerManager:
    className: spire-mgmt-external-server

upstream-spire-agent:
  server:
    port: 443

internal-spire-server:
  upstreamAuthority:
    spire:
      server:
        port: 443

external-spire-server:
  enabled: false
