# global:
#   spire:
#     clusterName: changeme

root-spire-server:
  kind: none
  controllerManager:
    className: spire-mgmt-external-server
    identities:
      clusterSPIFFEIDs:
        default:
          enabled: true
        child-servers:
          enabled: false
        oidc-discovery-provider:
          enabled: true
        test-keys:
          enabled: true

upstream-spire-agent:
  enabled: false

upstream-spiffe-csi-driver:
  enabled: false

internal-spire-server:
  enabled: false

downstream-spire-agent:
  bundleConfigMap: spire-bundle-upstream
  server:
    port: 443
#     address: spire-server.changeme

external-spire-server:
  enabled: false
