spiffe-oidc-discovery-provider:
  ingress:
    enabled: true

external-spire-server:
  ingress:
    enabled: true
  nodeAttestor:
    externalK8sPsat:
      defaults:
        serviceAccountAllowList:
          - spire-system:spire-agent
