apiVersion: v2
name: spire
description: >
  A Helm chart for deploying the complete Spire stack including: spire-server, spire-agent, spiffe-csi-driver, spiffe-oidc-discovery-provider and spire-controller-manager.
type: application
version: 0.20.0
appVersion: "1.9.4"
keywords: ["spiffe", "spire", "spire-server", "spire-agent", "oidc", "spire-controller-manager"]
home: https://github.com/spiffe/helm-charts-hardened/tree/main/charts/spire
sources:
  - https://github.com/spiffe/helm-charts-hardened/tree/main/charts/spire
icon: https://spiffe.io/img/logos/spire/icon/color/spire-icon-color.png
maintainers:
  - name: marcofranssen
    email: marco.franssen@gmail.com
    url: https://marcofranssen.nl
  - name: kfox1111
    email: Kevin.Fox@pnnl.gov
  - name: faisal-memon
    email: fymemon@yahoo.com
  - name: edwbuck
    email: edwbuck@gmail.com
kubeVersion: ">=1.21.0-0"
dependencies:
  - name: spire-lib
    repository: file://./charts/spire-lib
    version: 0.1.0
  - name: spire-server
    condition: spire-server.enabled
    tags:
    - simple
    repository: file://./charts/spire-server
    version: 0.1.0
  - name: spire-agent
    condition: spire-agent.enabled
    tags:
    - simple
    repository: file://./charts/spire-agent
    version: 0.1.0
  - name: spiffe-csi-driver
    condition: spiffe-csi-driver.enabled
    tags:
    - simple
    repository: file://./charts/spiffe-csi-driver
    version: 0.1.0
  - name: spiffe-oidc-discovery-provider
    condition: spiffe-oidc-discovery-provider.enabled
    tags:
    - simple
    - nestedRoot
    - nestedChildFull
    - nestedChildSecurity
    repository: file://./charts/spiffe-oidc-discovery-provider
    version: 0.1.0
  - name: tornjak-frontend
    condition: tornjak-frontend.enabled
    repository: file://./charts/tornjak-frontend
    version: 0.1.0
  - name: spire-server
    alias: root-spire-server
    condition: root-spire-server.enabled
    tags:
    - nestedRoot
    repository: file://./charts/spire-server
    version: 0.1.0
  - name: spire-server
    alias: external-root-spire-server-full
    condition: external-root-spire-server-full.enabled
    tags:
    - nestedChildFull
    repository: file://./charts/spire-server
    version: 0.1.0
  - name: spire-server
    alias: external-root-spire-server-security
    condition: external-root-spire-server-security.enabled
    tags:
    - nestedChildSecurity
    repository: file://./charts/spire-server
    version: 0.1.0
  - name: spire-server
    alias: internal-spire-server
    condition: internal-spire-server.enabled
    tags:
    - nestedRoot
    - nestedChildFull
    repository: file://./charts/spire-server
    version: 0.1.0
  - name: spire-server
    alias: external-spire-server
    condition: external-spire-server.enabled
    tags:
    - nestedRoot
    repository: file://./charts/spire-server
    version: 0.1.0
  - name: spire-agent
    alias: downstream-spire-agent-full
    condition: downstream-spire-agent-full.enabled
    tags:
    - nestedRoot
    - nestedChildFull
    repository: file://./charts/spire-agent
    version: 0.1.0
  - name: spire-agent
    alias: downstream-spire-agent-security
    condition: downstream-spire-agent-security.enabled
    tags:
    - nestedChildSecurity
    repository: file://./charts/spire-agent
    version: 0.1.0
  - name: spire-agent
    alias: upstream-spire-agent
    condition: upstream-spire-agent.enabled
    tags:
    - nestedRoot
    - nestedChildFull
    repository: file://./charts/spire-agent
    version: 0.1.0
  - name: spiffe-csi-driver
    alias: downstream-spiffe-csi-driver
    condition: downstream-spiffe-csi-driver.enabled
    tags:
    - nestedRoot
    - nestedChildFull
    - nestedChildSecurity
    repository: file://./charts/spiffe-csi-driver
    version: 0.1.0
  - name: spiffe-csi-driver
    alias: upstream-spiffe-csi-driver
    condition: upstream-spiffe-csi-driver.enabled
    tags:
    - nestedRoot
    - nestedChildFull
    repository: file://./charts/spiffe-csi-driver
    version: 0.1.0
annotations:
  artifacthub.io/category: security
  artifacthub.io/license: Apache-2.0
